/**
 * Copyright © 2016-2025 The Thingsboard Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.server.dao.gdt.audit.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * OIML R85 Compliance Report Model
 * Represents a compliance report for OIML R85 certification
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ComplianceReport implements Serializable {
    
    private static final long serialVersionUID = 1L;
    
    /**
     * Report ID
     */
    private String reportId;
    
    /**
     * Tenant ID
     */
    private String tenantId;
    
    /**
     * Report generation date
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    private Date generatedAt;
    
    /**
     * Report period start
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    private Date periodStart;
    
    /**
     * Report period end
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    private Date periodEnd;
    
    /**
     * Overall compliance status
     */
    private ComplianceStatus overallStatus;
    
    /**
     * Compliance percentage (0-100)
     */
    private double compliancePercentage;
    
    /**
     * Total audit events
     */
    private int totalAuditEvents;
    
    /**
     * Sealed devices
     */
    private int sealedDevices;
    
    /**
     * Unsealed devices
     */
    private int unsealedDevices;
    
    /**
     * Broken seals
     */
    private int brokenSeals;
    
    /**
     * Configuration changes detected
     */
    private int configurationChanges;
    
    /**
     * Data modifications detected
     */
    private int dataModifications;
    
    /**
     * Unauthorized access attempts
     */
    private int unauthorizedAttempts;
    
    /**
     * Critical events
     */
    private int criticalEvents;
    
    /**
     * Event summary by category
     */
    private Map<String, Integer> eventSummary;
    
    /**
     * Audit findings
     */
    private List<AuditFinding> findings;
    
    /**
     * Recommendations
     */
    private List<String> recommendations;
    
    /**
     * Digital signature of report
     */
    private String reportSignature;
    
    /**
     * Signature timestamp
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    private Date signatureTimestamp;
    
    /**
     * Generated by user
     */
    private String generatedBy;
    
    /**
     * Notes
     */
    private String notes;
    
    /**
     * Audit Finding Model
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class AuditFinding {
        private String findingId;
        private String category;
        private String severity;
        private String description;
        private String recommendation;
        private int occurrences;
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
        private Date detectedAt;
    }
    
    /**
     * Compliance Status Enum
     */
    public enum ComplianceStatus {
        FULLY_COMPLIANT("Completamente Conforme", "System is fully compliant with OIML R85"),
        COMPLIANT("Conforme", "System is compliant with OIML R85"),
        PARTIALLY_COMPLIANT("Parcialmente Conforme", "System has some compliance issues"),
        NON_COMPLIANT("No Conforme", "System is not compliant with OIML R85");
        
        private final String displayName;
        private final String description;
        
        ComplianceStatus(String displayName, String description) {
            this.displayName = displayName;
            this.description = description;
        }
        
        public String getDisplayName() {
            return displayName;
        }
        
        public String getDescription() {
            return description;
        }
    }
}
