///
/// Copyright © 2016-2025 The Thingsboard Authors
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

import { Component, OnInit, Inject } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { BatchType, CreateBatchRequest } from '../../../shared/models/batch.model';
import { TankAssetService } from '../../../shared/services/tank-asset.service';

@Component({
  selector: 'tb-create-batch-dialog',
  templateUrl: './create-batch-dialog.component.html',
  styleUrls: ['./create-batch-dialog.component.scss']
})
export class CreateBatchDialogComponent implements OnInit {

  batchForm: FormGroup;
  tanks: any[] = [];
  loading = false;

  batchTypes: { label: string; value: BatchType }[] = [
    { label: 'Recepción', value: 'receiving' },
    { label: 'Despacho', value: 'dispensing' }
  ];

  constructor(
    private fb: FormBuilder,
    private dialogRef: MatDialogRef<CreateBatchDialogComponent>,
    private tankAssetService: TankAssetService,
    @Inject(MAT_DIALOG_DATA) public data: any
  ) {}

  ngOnInit() {
    this.buildForm();
    this.loadTanks();
  }

  buildForm() {
    this.batchForm = this.fb.group({
      tankId: ['', Validators.required],
      batchType: ['receiving', Validators.required],
      openingLevel: ['', [Validators.required, Validators.min(0)]],
      openingTemperature: ['', [Validators.required, Validators.min(-50), Validators.max(150)]],
      openingApiGravity: ['', [Validators.required, Validators.min(4), Validators.max(99.9)]],
      openingBsw: [0, [Validators.min(0), Validators.max(100)]],
      destination: [''],
      transportVehicle: [''],
      sealNumbers: [''],
      notes: [''],
      operator: ['']
    });
  }

  loadTanks() {
    this.loading = true;
    this.tankAssetService.getAllTanksWithAttributes('Tank').subscribe({
      next: (tanks) => {
        this.tanks = tanks;
        this.loading = false;
      },
      error: (err) => {
        console.error('Error loading tanks:', err);
        this.loading = false;
      }
    });
  }

  onSubmit() {
    if (this.batchForm.valid) {
      const formValue = this.batchForm.value;
      
      // Find selected tank
      const selectedTank = this.tanks.find(t => t.asset.id.id === formValue.tankId);
      const tankName = selectedTank ? 
        (selectedTank.attributes.tankTag || selectedTank.asset.name) : 
        'Unknown Tank';

      // Parse seal numbers
      const sealNumbers = formValue.sealNumbers ? 
        formValue.sealNumbers.split(',').map((s: string) => s.trim()).filter((s: string) => s) : 
        undefined;

      const request: CreateBatchRequest = {
        batchNumber: '', // Will be generated by backend/service
        tankId: formValue.tankId,
        tankName,
        batchType: formValue.batchType,
        openingLevel: formValue.openingLevel,
        openingTemperature: formValue.openingTemperature,
        openingApiGravity: formValue.openingApiGravity,
        openingBsw: formValue.openingBsw,
        destination: formValue.destination || undefined,
        transportVehicle: formValue.transportVehicle || undefined,
        sealNumbers,
        notes: formValue.notes || undefined,
        operator: formValue.operator || undefined
      };

      this.dialogRef.close(request);
    }
  }

  onCancel() {
    this.dialogRef.close();
  }
}
